### ISSUE TITLE
Is the next version of cps.csv.gz going to resolve Tax-Calculator issue 1658?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/taxdata#162]
@andersonfrailey said in [this comment](https://github.com/open-source-economics/Tax-Calculator/issues/1658#issuecomment-350816124) that the CPS data needed more work.

**Comment by andersonfrailey** [comment]
No, I haven't been able to put a significant time into considering how to change our top coding procedures yet. Given that the deadline on the UBI project, I think the next version of the CPS should be available after #161 is merged so that Tax-Calculator and then TaxBrain can be updated accordingly.

After that, in no particular order, here are the major changes I have in mind for the CPS file:
* Create the CPS weights file using our own scripts
* Revisit our top coding procedure to address Tax-Calculator issue #1658
* Finish converting the CPS file creation scripts to Python
* Revisit how `n24` is calculated to address issue #157 
* Address missing variables in the CPS pointed out n #119 
* Add testing scripts to the repo

**Comment by martinholmer** [comment]
@andersonfrailey said:
>  I think the next version of the CPS should be available after #161 is merged so that Tax-Calculator and then TaxBrain can be updated accordingly.

But where is the pension income fix we discussed?  I thought we decided it should be included in the next version of `cps.csv.gz` to be included in Tax-Calculator.

**Comment by andersonfrailey** [comment]
Ah, you're right, @martinholmer. PR coming up.

**Comment by martinholmer** [comment]
@andersonfrailey,  I moved your post-4/1/2018 to-do list to issue #174, so that we can close this issue #162.
