### ISSUE TITLE
SOI wage targets: potential inflation adjustment issue

### ISSUE THREAD

**Issue by derrickchoe** [open-source-economics/taxdata#168]
Hi,

Thank you @MattHJensen, @andersonfrailey, and @hdoupe for your help introducing me to this repository. I'm in the final stages of adjusting the weights for the medical deduction project I brought up weeks ago. 

While working with taxdata, I noticed that we set 12 targets for total wages by AGI bracket. 

Past 2014, these targets grow with our CBO wage projections:
```
Wage_1 = return_projection.WAGE_1[i]*cbo_growth_rates.Wages[i+1]
Wage_2 = return_projection.WAGE_2[i]*cbo_growth_rates.Wages[i+1]
```
When matching the 2011 PUF to these targets, we group observations based on these AGI cutoffs:
```
wage_1 = np.where(puf.e00100 <= 0, puf.e00200, 0) * s006
wage_2 = np.where((puf.e00100 > 0) & (puf.e00100 <= 10000),
                      puf.e00200, 0) * s006
```

I might have missed something, but I'm not sure that this takes increasing AGIs over time into account. 
In the [Stage II targets file](https://github.com/open-source-economics/taxdata/blob/master/stage1/Stage_II_targets.csv), the total wages earned by people with less than $10,000 in AGI is growing proportionally with all other AGI buckets. Instead, I imagine that it grows slower, since people are earning more in more in nominal terms. These bracket cutoffs are fixed, so as incomes grow, the share of people with incomes in the lower brackets should fall in relation to the total population.  

I ran into a similar issue when matching the number of medical deduction takers by AGI group. The target matching should be fine until 2014 since all SOI estimates are reported in nominal terms. Past 2014, I think that the solution is to continue inflating each AGI group's total wages by the CBO wage projection (so they continue to grow proportionally), but adjust the tax filer AGIs in the PUF to 2014 dollars in order to account for inflation. 

This way, the tax filers in the < $10,000 bracket are interpreted as filers with <$10,300 AGI if wage growth was, say, 3% in 2015. 

Please let me know if this makes sense-- I may be misinterpreting things. If I have identified an issue that should be addressed, I'm happy to write the code fixing this.

Thanks,

Derrick

**Comment by andersonfrailey** [comment]
Just to make sure I understand, basically what you're saying, @derrickchoe, is that because we don't either blow up AGI before finding the weighted total in each bracket, or increase the AGI brackets to account for inflation, we're overestimating the total wages in lower AGI bins (and thus underestimating in higher brackets I'd imagine). And we should thus increase the AGI bins to account for this. Is that roughly what you had in mind? If so, if you're willing to experiment a bit I'd welcome any insights you could provide on what effect bracket adjustments would have. I did just have one thought though that may address your concerns.

`e00100` is no longer an accurate representation of each units AGI as soon as we start applying growth factors to other income variables. At no point do we recalculate AGI during the extrapolation before finding wage totals by AGI bin so the actual AGI of each person in a bin is higher than the AGI we use to assign them to an AGI bin.

Lets say a unit has AGI or $10,000 in the 2011 PUF.  This will put them in the $0-10,000 AGI bracket when we do our wage targeting. As we move through the years, we'll increase their wages and other sources of income, but never recalculate their AGI. So this person will still be considered in the $0-10,000 AGI bracket, but in reality their AGI may be closer to say $10,300.

Doesn't this accomplish what increasing AGI brackets would?

**Comment by derrickchoe** [comment]
@martinholmer @andersonfrailey 

Hi all, 

Thanks for taking the time to look into this! @andersonfrailey, I believe that my original concern is addressed in your explanation: 

> e00100 is no longer an accurate representation of each units AGI as soon as we start applying growth factors to other income variables. At no point do we recalculate AGI during the extrapolation before finding wage totals by AGI bin so the actual AGI of each person in a bin is higher than the AGI we use to assign them to an AGI bin.

I had missed the fact that e00100 isn't inflated throughout the matching process. So each wage bin can be expected to remain the same size throughout each tax year. Knowing this, I don't believe there are any fixes necessary.

Closing this now-- thanks again!
