### ISSUE TITLE
Fixes for next version of Tax-Calculator

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/taxdata#182]
@andersonfrailey,  I'm hoping we can incorporate three data bug fixes in the next version of Tax-Calculator.
Here is my wish list:

- fix problem with PUF nu18,n1820,n21 values vs XTOT values reported in #149 
- fix problem with CPS n24 values vs nu18 values reported in #157 
- fix problem of missing 2014 CPS weights reported in #176 

Does it seem reasonable to expect that these issues can be fixed in the near future?
If so, what kind of schedule do you think makes sense for me to expect?  (Knowing your schedule will help me budget my time for making changes in Tax-Calculator logic.)

**Comment by martinholmer** [comment]
@andersonfrailey said:
>> fix problem of missing 2014 CPS weights reported in #176
>
> I'm not anticipating getting any clarifying help from John with this, and the Fortran code I have still doesn't compile on my machine, but I am making progress in creating the CPS file myself. If I continue to make progress at my current rate I should have it ready in the next couple of weeks and thus should be able to have 2014 weights then.

Sorry I didn't make this clear, but I'm only asking for what you said you'd do last week.  In issue #176, we had this exchange about a week ago:
@martinholmer asked:
>> As for the [missing] 2014 weights column [in cps_weights.csv.gz file], I can copy over the weights from the CPS file [multiplying by 100 and rounding them to the nearest integer].
>
> Actually, on second thought, this would be a big help to Tax-Calculator.
> You can do this even though #145 is still unresolved, right?

To which @andersonfrailey replied:
> Yes. I can open up a PR that does this today.

**Comment by martinholmer** [comment]
@andersonfrailey said:
>> fix problem with PUF nu18,n1820,n21 values vs XTOT values reported in #149
>
> I still haven't pinpointed the cause of this bug and it's relatively low on my priority list compared to tasks like creating the CPS weights file, so I'd say this will take about a month to get to.

I don't understand why this is "low on [your] priority list" now that we have the CPS benefits data working.
This bug was reported over two months ago on February 12, 2018.  We agreed then to put off working on it until after April 1st, but I don't view it as low priority now that the April 1st deadline has passed.  The PUF data are still the premier input data source for Tax-Calculator and #149 shows these data are internally inconsistent.   I think fixing this data bug should be a very high priority.  Why do you think it should have a low priority?

**Comment by andersonfrailey** [comment]
>Sorry I didn't make this clear, but I'm only asking for what you said you'd do last week. In issue #176, we had this exchange about a week ago:

Ah right, sorry. Slipped my mind. See PR #184.

>I don't understand why this is "low on [your] priority list" now that we have the CPS benefits data working.

I have this lower on my priority list because I believe creating the CPS weights file is a larger milestone for this repo than fixing this discrepancy. Once we can create the CPS weights on our own we can then move the CPS file creation from SAS to Python, making all of our work fully replicable.

Additionally, `nu18`, `n1821`, and `n21` are all used exclusively for UBI analysis and most of the UBI work conducted to date has been done using the CPS. We can also be confident that `XTOT` is correct because it is pulled from the IRS-SOI.

As a worst case, this bug could be indicative of a larger error in the matching process, but there is no evidence of that to my knowledge.

This of course doesn't mean that I am completely ignoring the bug, I've done some work to try and fix it/figure out the root cause, I'm just focusing more of my attention on creating the CPS weights file.
