### ISSUE TITLE
PUF record with zero weight

### ISSUE THREAD

**Issue by andersonfrailey** [open-source-economics/taxdata#239]
@martinholmer noticed when writing tests for the weights that there is one record with a zero weight. I did some data exploration and believe I found the reason.

The record in question, located at index 35680, has a weight of zero from 2011 to 2015 and a weight of one for all years after that. Looking at the `cps-matched-puf.csv` file, I found that before rounding that record has a weight of 0.00487, which is ultimately rounded down to zero in the PUF and the `WT2011` column of `puf_weights.csv.gz`. We do not have a version of the PUF weights before they are rounded, but I think it's safe to say that the unit in question has a nonzero weight until we round.

We have records with weights < 1 because during the matching process we try and "use up" the entirety of a record's weights. By this I mean that we keep using a record in matches until its weight is at or below some epsilon (0.001). See `puf_data/StatMatch/phase2.py` for details.

Off the top of my head, there are a couple solutions to this. We could enforce a minimum weight of 1 after rounding, stop rounding all together (this is the least desirable in my opinion because we are aiming at minimizing file size), or increase the epsilon value in phase 2 of our matching process. My only worry about the last option is I'm not sure what affect that change would have on the match results.

You can see the notebook I did my data exploration [here](http://nbviewer.jupyter.org/github/andersonfrailey/Notebook-Uploads/blob/master/zerowt.ipynb).

**Comment by martinholmer** [comment]
@andersonfrailey,  Thanks for your detailed explanation in #239 of why there is one PUF record with zero weight (in the rounded `puf_weights.csv.gz` file) in every year.

Your investigation shows that the weight-creation process is working as designed.
I see no reason to do anything about this situation because everything is correct.
We are not going to reduce file sizes much by trying to eliminate this record and we run the risk of making a mistake, so let's not go there.

@andersonfrailey, do you agree that this is the best course of (in)action?
If so, just close #239 so we have a record of your helpful investigation.

**Comment by andersonfrailey** [comment]
@martinholmer I agree that we shouldn't make any changes right now. Closing.
