### ISSUE TITLE
Is Social Security Disability Insurance (SSDI) in taxdata?

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/taxdata#282]
The [taxdata documentation](http://open-source-economics.github.io/Tax-Calculator/) only refers to the OASDI component of Social Security, and Schedule R regarding disability. Is SSDI part of any other taxdata input?

Some info on SSDI:
* It totaled [$143B in 2017 covering 8.6M people.](https://www.cbpp.org/research/social-security/chart-book-social-security-disability-insurance)
* Searching for [ssdi] yields no results in taxdata, C-TAM, or Tax-Calculator.
* The [2016 ACS data dictionary](https://www2.census.gov/programs-surveys/acs/tech_docs/pums/data_dict/PUMS_Data_Dictionary_2012-2016.pdf) describes `SSP` as "Social Security income past 12 months;" this is the only reference to Social Security, and disability fields are about reported [disability classifications](https://www.census.gov/topics/health/disability/guidance/data-collection-acs.html). This suggests it might lump together OASDI and SSDI.
* The IRS's description of [Social Security taxability](https://www.irs.gov/newsroom/are-social-security-benefits-taxable) doesn't distinguish between OASDI and SSDI.
* The [Survey of Income and Program Participation (SIPP)](https://www.census.gov/content/dam/Census/library/publications/2017/demo/p70br-144.pdf) separates OASDI from SSDI.

Is it possible that what taxdata calls OASDI includes SSDI?

**Comment by martinholmer** [comment]
@MaxGhenis asked in taxdata issue #282:
> Is it possible that what taxdata calls OASDI includes SSDI?

Yes.  `OASDI` is the standard acronym for "Old-Age, Survivors, and Disability Insurance", which is the official name of the government program that people call "Social Security".

**Comment by martinholmer** [comment]
@MaxGhenis said:
> * The [Survey of Income and Program Participation (SIPP)](https://www.census.gov/content/dam/Census/library/publications/2017/demo/p70br-144.pdf) separates OASDI from SSDI.

That's not true.  If you look at the Table 1 in the document you pointed to, the headings are "Social Security (retirement benefits)" and "Social Security (disability benefits)".  As far as I could see, there was no use of the acronym OASDI in that SIPP document.

**Comment by MaxGhenis** [comment]
My mistake! I thought OASDI was old-age only. Closing.

Would it be within scope of taxdata or C-TAM to use SIPP to impute the disability vs. retirement split of OASDI? For example I've heard more tolerance/appetite for replacing SSDI with UBI compared to retirement benefits.

**Comment by MaxGhenis** [comment]
Looks like [SSA uses](https://www.ssa.gov/oact/STATS/index.html) the acronym OASI for "Old-Age and Survivors Insurance" and DI for "Disability Insurance."

**Comment by martinholmer** [comment]
@MaxGhenis said in taxdata issue #282:
> Looks like [SSA uses](https://www.ssa.gov/oact/STATS/index.html) the acronym OASI for "Old-Age and Survivors Insurance" and DI for "Disability Insurance."

Yes, they split the three programs up that way because there is an OASI Trust Fund and a separate DI Trust Fund with separate payroll tax rates for the two trust funds.  The two trust funds exist because OASI was established in the original 1935 social security act, while DI was added later in 1956.

**Comment by martinholmer** [comment]
@MaxGhenis said in taxdata issue #282:
> I've heard more tolerance/appetite for replacing SSDI with UBI compared to [OASI] retirement benefits.

I'm not surprised that you've heard that.  But before you start analyzing UBI reforms that repeal just DI benefits (which you could do if you created a taxdata fork that somehow separated OASI benefits from DI benefits and created a Tax-Calculator fork that computed OASI payroll taxes separately from DI payroll taxes), you should spend some time looking at the **distribution** of DI benefits.  There are some very large DI benefits (relative to likely UBI payments) because, like OASI benefits, the DI benefit is based on a person's average indexed monthly earnings (AIME) computed over the person's lifetime.  So, if a person who had high lifetime earnings becomes disabled (like a dentist who suffers from hand damage and is no longer able to work as a dentist), that person will have earned a high DI benefit.  People like that will be suffer a major income reduction from a UBI reform that repeals DI benefits, and they will feel wronged because they "earned" their high DI benefit through the high DI payroll tax ("social insurance premium") they paid each year of their working life.
